{
 "title": "default dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Error",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT SUM(error_count) \r\nFROM data_quality_stats\r\nWhere (ingestion_timestamp IS NOT NULL) AND (ingestion_timestamp IS NOT NULL)\r\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "Error By Severity ",
   "type": "barchart",
   "gridPos": { "x": 6, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT SUM(error_count), error_criticality \r\nFROM data_quality_stats \r\nWHERE NOT error_criticality = 'None' AND ingestion_timestamp IS NOT NULL\r\nGROUP BY error_criticality LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Error count overtime",
   "type": "timeseries",
   "gridPos": { "x": 14, "y": 0, "w": 10, "h": 8 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT Sum(error_count) as Total_Error, ingestion_timestamp\r\nFROM \r\n  (SELECT error_count, ingestion_timestamp, error_criticality \r\n\tFROM data_quality_stats\r\n\tWhere (ingestion_timestamp IS NOT NULL) AND (error_count > 0)\r\n\tLIMIT 5000 ) as base\r\nWHERE (ingestion_timestamp IS NOT NULL) \r\nGROUP BY ingestion_timestamp\r\nLIMIT 5000\r\n"
    }
   ]
  },
  {
   "title": "Input data",
   "type": "table",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT * FROM input_data LIMIT 50 "
    }
   ]
  }
 ]
}