{
 "title": "Data Quality Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total Errors (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT SUM(error_count) AS total_errors FROM data_quality_stats "
    }
   ]
  },
  {
   "title": "Error By Severity",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT error_criticality, SUM(error_count) AS error_count FROM data_quality_stats GROUP BY error_criticality ORDER BY error_criticality"
    }
   ]
  },
  {
   "title": "Error Count Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT ingestion_timestamp AS time, error_count FROM data_quality_stats ORDER BY ingestion_timestamp ASC"
    }
   ]
  },
  {
   "title": "Error Rate Trend (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT ingestion_timestamp AS time, ROUND(CAST(error_rate * 100 AS numeric), 2) AS error_rate FROM data_quality_stats ORDER BY ingestion_timestamp ASC"
    }
   ]
  },
  {
   "title": "Clean vs Corrupt Rows Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT ingestion_timestamp AS time, (total_rows - error_count) AS clean_rows, error_count AS corrupt_rows FROM data_quality_stats ORDER BY ingestion_timestamp ASC"
    }
   ]
  },
  {
   "title": "Error Rate Per Ingestion",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT ingestion_timestamp, file_name, total_rows, error_count, ROUND(CAST(error_rate * 100 AS numeric), 2) AS error_rate, error_criticality, is_schema_valid FROM data_quality_stats ORDER BY ingestion_timestamp DESC"
    }
   ]
  },
  {
   "title": "Schema Errors Alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT ingestion_timestamp AS time, CASE WHEN is_schema_valid = false THEN 1 ELSE 0 END AS schema_error FROM data_quality_stats ORDER BY ingestion_timestamp ASC"
    }
   ]
  },
  {
   "title": "Full Error Details (data_quality_errors)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT s.ingestion_timestamp, s.file_name, s.error_criticality, s.total_rows, s.error_count, e.error_category, e.column_name, e.row_count, e.expectation_type FROM data_quality_errors e JOIN data_quality_stats s ON e.stat_id = s.id  ORDER BY s.ingestion_timestamp DESC"
    }
   ]
  },
  {
   "title": "Data Quality Stats (data_quality_stats)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "dataset": "predictions_db",
     "rawSql": "SELECT id, ingestion_timestamp, file_name, total_rows, error_count, ROUND(CAST(error_rate * 100 AS numeric), 2) AS error_rate, error_criticality, is_schema_valid FROM data_quality_stats ORDER BY ingestion_timestamp DESC"
    }
   ]
  }
 ]
}